# SPDX-FileCopyrightText: 2024 CERN
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    ".gitignore",
    ".dockerignore",
    "haproxy.cfg",
    "configs_templates/*.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 CERN"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "provider_docs/*.md"
precedence = "override"
SPDX-FileCopyrightText = "2024 CERN"
SPDX-License-Identifier = "CC-BY-4.0"
